In [65]:
a = input()
print(a)

5
5


In [66]:
a = input()
print(a)

Hello
Hello


In [68]:
a = int(input())
b = int(input())
print(a+b)

5
9
14


In [75]:
a = eval(input())
print(a[2])

[1, 2, 3, 4, 5]
3


In [76]:
eval("5+3")

8

In [79]:
a = input().split()
print(a)

1 2 3 4 5
['1', '2', '3', '4', '5']


In [81]:
a = list(map(int, input().split()))
print(a[2])

1 2 3 4 5
3


In [82]:
a = [1, 2, 3, 4, 5]

In [83]:
a

[1, 2, 3, 4, 5]

In [89]:
a[::-1]

[5, 4, 3, 2, 1]

In [91]:
a = [1, 2, 3, 4, 5]
b = (1, 2, 3, 4, 5)
print(b[::-1])
a[0] = 4
print(a)

(5, 4, 3, 2, 1)
[4, 2, 3, 4, 5]


In [94]:
a = {1, 3, 2, 4, 2, 1, 3, 2}
b = {2, 3, 4, 1, 5}
print(a.union(b))

{1, 2, 3, 4, 5}


In [96]:
a = {"Hi": 1, "C":"Python"}
print(a["Hi"])

1


In [53]:
a = ["Hello", 1, 3, 2, "World"]
for i in a:
    print(i, end=" ")
print()
for i in range(len(a)):
    print(a[i], end=" ")
print()
print(*a, sep=" ;; ")

Hello 1 3 2 World 
Hello 1 3 2 World 
Hello ;; 1 ;; 3 ;; 2 ;; World


In [107]:
a = None
print(a)

None


In [109]:
for i in range(10):
    if i == 5:
        continue
    elif i == 7:
        break
    print(i)

0
1
2
3
4
6


In [113]:
a = 4
b = 5
print(a, b)
a, b = b, a
print(a, b)

4 5
5 4


In [114]:
a = [[1, 2], [3, 4]]
b = [[3, 4], [5, 6]]
print(a[0][1], b[0][1])

2 4


In [116]:
c = [[0]*2]*2
for i in range(len(a)):
    for j in range(len(a[i])):
        c[i][j] = a[i][j] + b[i][j]
print(c)

[[4, 6], [8, 10]]


In [128]:
print([[0]*2 for i in range(2)])

[[0, 0], [0, 0]]


In [119]:
import numpy as np
a  = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [5, 6]])
print(a)
print(b)
print(np.dot(a, b))

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
[[13 16]
 [29 36]]


In [130]:
i = 5
j = 3
if i == 5 or j == 9:
    print(True)

True


In [120]:
import time 
a = np.random.randn(100, 100)
b = np.random.randn(100, 100)
start = time.time()
c1 = np.dot(a, b)
end = time.time()
print("Time taken by Numpy multiplication:", end-start)
c2 = np.zeros(a.shape)
start = time.time()
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c2[i][j] = 0
        for k in range(a.shape[1]):
            c2[i][j] += a[i][k]*b[k][j]
end = time.time()
print("Time taken by for loops:", end-start)

Time taken by Numpy multiplication: 0.001992940902709961
Time taken by for loops: 1.2968823909759521


In [121]:
a = np.array([[1.5, 2.0], [3.7, 5.8]])

In [122]:
a

array([[1.5, 2. ],
       [3.7, 5.8]])

In [126]:
np.square(a)

array([[ 2.25,  4.  ],
       [13.69, 33.64]])

In [136]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [1, 4]])
print(a+b)

[[4 6]
 [4 8]]


In [138]:
print(np.dot(a,b))
print(a.dot(b))

[[ 5 12]
 [13 28]]
[[ 5 12]
 [13 28]]


In [15]:
print(np.multiply(a, b))

[[ 3  8]
 [ 3 16]]


In [24]:
a*b

array([[ 3,  8],
       [ 3, 16]])

In [16]:
print(np.cross(a, b))

[-2  8]


In [17]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones((3, 5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
np.ones((3, 5))*3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [26]:
np.random.randn(3, 3)

array([[-0.38679392, -0.583226  , -0.35523128],
       [-0.34142687, -2.13450931, -1.75399012],
       [-0.72017701, -0.72939705, -1.72069872]])

In [14]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
c = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(b/c)
print(b/a)
print(a.shape)
a = a.reshape(4, 1)
print(a.shape)
print(b/c)
print(b/a)

[[1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [4.         1.5        0.66666667 0.25      ]]
[[1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [4.         1.5        0.66666667 0.25      ]]
(4,)
(4, 1)
[[1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [4.         1.5        0.66666667 0.25      ]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [52]:
import math
print(math.ceil(5.4))
print(math.floor(5.4))
print(round(5.5))
print(math.sqrt(9))
print(math.pow(2, 3))
print(math.tan(math.pi))
print(math.pi)
print(math.exp(3))

6
5
6
3.0
8.0
-1.2246467991473532e-16
3.141592653589793
20.085536923187668


In [54]:
a = np.random.randn(5, 5)

In [55]:
a

array([[-0.2971488 , -1.91855187,  0.62182387, -0.39994845, -0.36324536],
       [-0.53667001, -1.8662277 , -1.52422914,  0.18810215,  0.92740132],
       [-0.0871411 ,  0.13105733,  0.74915828,  1.88106648,  0.54926997],
       [ 0.40677444,  1.10153888,  0.34263376,  0.86717107,  0.26423561],
       [-0.31834278,  0.45355066,  2.26316367, -0.05601104,  0.40580528]])

In [55]:
np.ceil(a)

array([[ 1., -1., -0.,  2.,  1.],
       [ 1.,  3.,  2.,  1., -0.],
       [ 1., -0., -1.,  2.,  2.],
       [ 1., -1.,  2., -0.,  2.],
       [ 1., -0., -1.,  1.,  1.]])

In [56]:
np.floor(a)

array([[ 0., -2., -1.,  1.,  0.],
       [ 0.,  2.,  1.,  0., -1.],
       [ 0., -1., -2.,  1.,  1.],
       [ 0., -2.,  1., -1.,  1.],
       [ 0., -1., -2.,  0.,  0.]])

In [58]:
np.exp(a)

array([[1.35045096, 0.33146151, 0.8533665 , 5.89156536, 1.75191761],
       [1.30512957, 9.03779016, 2.72701561, 1.00297227, 0.84862732],
       [1.18014423, 0.58387266, 0.16121342, 3.94178614, 2.85761249],
       [1.1858352 , 0.27021358, 7.04872614, 0.69778627, 4.87215168],
       [2.3794573 , 0.38316908, 0.32333445, 2.07785052, 1.90191125]])

In [57]:
np.round(a)

array([[ 0., -1., -0.,  2.,  1.],
       [ 0.,  2.,  1.,  0., -0.],
       [ 0., -1., -2.,  1.,  1.],
       [ 0., -1.,  2., -0.,  2.],
       [ 1., -1., -1.,  1.,  1.]])

In [59]:
np.square(a)

array([[9.02633432e-02, 1.21935390e+00, 2.51432291e-02, 3.14537932e+00,
        3.14396787e-01],
       [7.09169275e-02, 4.84622665e+00, 1.00642594e+00, 8.80817720e-06,
        2.69403476e-02],
       [2.74355023e-02, 2.89521879e-01, 3.33072058e+00, 1.88137971e+00,
        1.10247161e+00],
       [2.90522954e-02, 1.71228373e+00, 3.81361106e+00, 1.29486574e-01,
        2.50758520e+00],
       [7.51467818e-01, 9.20216042e-01, 1.27479464e+00, 5.34849357e-01,
        4.13268081e-01]])

In [60]:
np.tan(a)

array([[ 3.09816867e-01, -1.98555821e+00, -1.59908624e-01,
        -4.86501996e+00,  6.27940398e-01],
       [ 2.72781287e-01, -1.36974621e+00,  1.56845140e+00,
         2.96786606e-03, -1.65625162e-01],
       [ 1.67168243e-01, -5.96812391e-01,  3.84833757e+00,
         4.95446510e+00,  1.74326071e+00],
       [ 1.72117378e-01, -3.72527982e+00, -2.48884755e+00,
        -3.76222968e-01, -7.84927804e+01],
       [ 1.17783084e+00, -1.42616751e+00, -2.11464066e+00,
         8.97322695e-01,  7.48997657e-01]])

In [61]:
np.power(a, 3)

array([[ 2.71185911e-02, -1.34646372e+00, -3.98686544e-03,
         5.57839857e+00,  1.76285726e-01],
       [ 1.88853426e-02,  1.06685545e+01,  1.00965438e+00,
         2.61414134e-08, -4.42185799e-03],
       [ 4.54432489e-03, -1.55783725e-01, -6.07865228e+00,
         2.58056429e+00,  1.15758029e+00],
       [ 4.95188645e-03, -2.24059621e+00,  7.44739857e+00,
        -4.65947636e-02,  3.97085058e+00],
       [ 6.51426737e-01, -8.82743849e-01, -1.43932989e+00,
         3.91153497e-01,  2.65673229e-01]])

In [57]:
np.sqrt(a.astype(np.complex))

array([[0.        +0.54511357j, 0.        +1.385118j  ,
        0.78855809+0.j        , 0.        +0.63241478j,
        0.        +0.6026984j ],
       [0.        +0.73257765j, 0.        +1.36609945j,
        0.        +1.23459675j, 0.43370745+0.j        ,
        0.96301678+0.j        ],
       [0.        +0.29519672j, 0.36201842+0.j        ,
        0.8655393 +0.j        , 1.37151977+0.j        ,
        0.7411275 +0.j        ],
       [0.63778871+0.j        , 1.04954222+0.j        ,
        0.58534926+0.j        , 0.93122021+0.j        ,
        0.51403853+0.j        ],
       [0.        +0.56421873j, 0.6734617 +0.j        ,
        1.50438149+0.j        , 0.        +0.23666652j,
        0.63702848+0.j        ]])

In [63]:
np.abs(a)

array([[0.30043858, 1.10424359, 0.15856617, 1.77352173, 0.56071097],
       [0.26630232, 2.20141469, 1.00320783, 0.00296786, 0.16413515],
       [0.16563666, 0.53807237, 1.82502619, 1.37163396, 1.04998648],
       [0.17044734, 1.3085426 , 1.95284691, 0.35984243, 1.58353566],
       [0.86687243, 0.95927892, 1.12906804, 0.73133396, 0.6428593 ]])

In [65]:
np.arctan(a)

array([[ 0.29185912, -0.83489739, -0.15725691,  1.05738204,  0.51102939],
       [ 0.26026221,  1.14441095,  0.78699951,  0.00296785, -0.16268457],
       [ 0.16414634, -0.49363963, -1.06953811,  0.9408337 ,  0.80977714],
       [ 0.1688249 , -0.91826332,  1.0975371 , -0.34541608,  1.00753775],
       [ 0.71420819, -0.76461745, -0.84594591,  0.63144742,  0.57133901]])

In [153]:
a = [1, 2, 3, 4, 5]
print(sum(a))

15


In [154]:
print(sum([[1, 2, 3], [4, 5, 6]]))

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [158]:
x = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(x.sum(axis = 1))

[15 20]


In [84]:
a = np.random.randn(5, 5)
print(a)
print(np.where(a>0, 0, a))

[[ 0.09059882  1.42693653 -0.31870672  0.84418867 -0.66791519]
 [ 0.57853591 -0.15105494  1.17787743 -0.05491664 -1.38606276]
 [ 0.10722373 -0.56492081  1.17838051  0.53447346 -0.86981543]
 [ 0.52092059  0.81637912 -1.05893036 -0.00526652 -0.79980882]
 [ 0.91487263 -0.46834145 -0.07189643 -1.63502259 -2.10841236]]
[[ 0.          0.         -0.31870672  0.         -0.66791519]
 [ 0.         -0.15105494  0.         -0.05491664 -1.38606276]
 [ 0.         -0.56492081  0.          0.         -0.86981543]
 [ 0.          0.         -1.05893036 -0.00526652 -0.79980882]
 [ 0.         -0.46834145 -0.07189643 -1.63502259 -2.10841236]]


In [162]:
a = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])
b = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])
print(a == b)
print((a - b) == 0)
print(a ^ b)
print((a ^ b).sum() == 0)

[[ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]]
[[0 0 0 0]
 [0 0 0 0]]
True


In [174]:
print(a)
print(a.T)
# print(a.T[0][:])
# print(a.T[:][0])
print(a.T[:, 1])
print(a.T[1:3, :])

[[1 2 3 4]
 [2 3 4 5]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[2 3 4 5]
[[2 3]
 [3 4]]


In [98]:
a = [1, 2, 3, 4]

In [101]:
a[-3]

2

In [175]:
a = np.array([[1, 2], [4, 5], [7, 8]])
print(a.shape)
print(a)
print(a.reshape(2,3))
print(a.reshape(6,))

(3, 2)
[[1 2]
 [4 5]
 [7 8]]
[[1 2 4]
 [5 7 8]]
[1 2 4 5 7 8]


In [114]:
a = np.array([[-1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(np.max(a, axis = 1))

[5 6]


In [176]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.linalg.eig(a))
print(np.linalg.eigvals(a))

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]


In [177]:
a  = np.array([0.5,1, 0, 1/np.sqrt(2)])
print(np.argmax(a))
print(np.arcsin(a))

1
[0.52359878 1.57079633 0.         0.78539816]


In [127]:
np.array([1+2j, 3+4j])

array([1.+2.j, 3.+4.j])

In [185]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(a)
print(b)
print((a*b).sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
15


In [161]:
a = np.array([[1, 2, 3, 4], [5, -1, -3, -5]])
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))
print(np.max(a, axis = 0))
print(np.max(a, axis = 1))

[ 1 -1 -3 -5]
[ 1 -5]
[5 2 3 4]
[4 5]


In [182]:
w = np.array([1, 2, 3, 4, 5])
x = np.array([4, 5, 2, 1, 3])
print(np.dot(w, x).sum())

39


In [191]:
def myFunc(a):
    return a**2+2
a = [1, 2, 3, 4, 5]
a = list(map(myFunc, a))
print(a)
b = [1, 2, 3, 4, 5]
b = [i**2+2 for i in b]
print(b)

[3, 6, 11, 18, 27]
[3, 6, 11, 18, 27]


In [26]:
a, b = 4, 5
if a == 4 and b == 5:
    print(True)
a, b = 1, 1
print(a ^ b)

True
0


In [27]:
a = np.random.randn(4, 5)

In [28]:
a.T

array([[-0.2224617 , -1.38483758,  0.97551913, -0.23715094],
       [-2.32724657,  1.09728048,  1.11724685,  0.67080741],
       [-1.35263551, -0.59518874, -0.81608646, -0.0243323 ],
       [-0.1012002 ,  0.98660111, -1.38791872, -1.87319126],
       [-0.83178039,  0.50843505,  0.45436548, -0.35670327]])

In [34]:
a.T[3:5, :]

array([[-0.1012002 ,  0.98660111, -1.38791872, -1.87319126],
       [-0.83178039,  0.50843505,  0.45436548, -0.35670327]])

In [29]:
a

array([[-0.2224617 , -2.32724657, -1.35263551, -0.1012002 , -0.83178039],
       [-1.38483758,  1.09728048, -0.59518874,  0.98660111,  0.50843505],
       [ 0.97551913,  1.11724685, -0.81608646, -1.38791872,  0.45436548],
       [-0.23715094,  0.67080741, -0.0243323 , -1.87319126, -0.35670327]])

In [56]:
class rectangle:
    def __init__(self, l, b):
        self.l = l
        self.b = b
    def area(self):
        return self.l*self.b
    def perimeter(self):
        return 2*(self.l+self.b)

In [57]:
myRect = rectangle(5, 4)
print(myRect.area())
print(myRect.perimeter())

20
18


In [58]:
class square(rectangle):
    def __init__(self, a):
        self.l = self.b = a


In [59]:
mySquare = square(5)
print(mySquare.area())
print(mySquare.perimeter())

25
20


In [16]:
mySquare._l

5

In [25]:
class complex_number:
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
    def __add__(self, c):
        self.real += c.real
        self.imag += c.imag
        return self
    def __sub__(self, c):
        self.real -= c.real
        self.imag -= c.imag
        return self
    def __mul__(self, c):
        return complex_number(self.real*c.real - self.imag*c.imag, self.real*c.imag + self.imag*c.real)
    def __str__(self):
        if self.imag >= 0:
            return (str(self.real) + " + " + str(self.imag) + "j")
        else:
            return (str(self.real) + " - " + str(-self.imag) + "j")

In [131]:
print(complex_number(5, 2) + complex_number(1, 5))

6 + 7j


In [27]:
x = [-6, -3, -1, 0, 2, 4, 5]
y = list(map(lambda x:x**2, x))
print(x)
print(y)

[-6, -3, -1, 0, 2, 4, 5]
[36, 9, 1, 0, 4, 16, 25]


In [28]:
print(sorted(x, key=lambda x:x**2))

[0, -1, 2, -3, 4, 5, -6]


In [62]:
import math
for i in range(2, 101):
    for j in range(2, math.floor(math.sqrt(i))+1):
        if i%j == 0:
            break
    else:
        print(i, end = " ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [55]:
i = 0.0
while i <= 1.0:
    print(i)
    i = round(i + 0.1, 1)

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0


In [43]:
[print(i*0.1, end = " ") for i in range(10)]

0.0 0.1 0.2 0.30000000000000004 0.4 0.5 0.6000000000000001 0.7000000000000001 0.8 0.9 

[None, None, None, None, None, None, None, None, None, None]

In [54]:
import numpy as np
print(np.arange(0, 1, 0.1))


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [60]:
x = [-3, 4, -5, 2, 1, 0]
y = list(map(lambda x:x**2, x))
print(y)

[9, 16, 25, 4, 1, 0]


In [82]:
print(np.sin(0))

0.0


In [85]:
from collections import Counter

In [88]:
a = Counter([1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 4, 3, 4, 3, 5])
print(a)

Counter({1: 7, 2: 4, 4: 2, 3: 2, 5: 1})


In [95]:
from itertools import combinations
a = [1, 2, 3, 4, 5]
print(list(combinations(a, 3)))

[(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (1, 4, 5), (2, 3, 4), (2, 3, 5), (2, 4, 5), (3, 4, 5)]


In [103]:
a = [1, 2, 3, 4, 5]
i = iter(a)
print(next(i))
print(next(i))
print(next(i))
print(next(i))
print(next(i))

1
2
3
4
5


In [111]:
from collections import defaultdict
a = defaultdict(lambda:4)
print(a)
print(a[3])
print(a)

defaultdict(<function <lambda> at 0x00000207708FC0D0>, {})
4
defaultdict(<function <lambda> at 0x00000207708FC0D0>, {3: 4})


In [113]:
from collections import deque
a = deque()
a.push_back(5)

AttributeError: 'collections.deque' object has no attribute 'push_back'

In [127]:
a =[print(i*(10**i - 1)//9) for i in range(1, 6)]

1
22
333
4444
55555


In [130]:
[print(((10**i - 1)//9)**2) for i in range(1, 6)]
print()

1
121
12321
1234321
123454321



In [126]:
for i in range(1, 6):
    print(i)

1
2
3
4
5


In [137]:
from collections import Counter
a = [1, 1, 2, 1, 2, 1, 2, 4, 2, 1, 1, 2, 4, 2, 1]
print(Counter(a))

Counter({1: 7, 2: 6, 4: 2})


In [146]:
from collections import defaultdict
a = defaultdict(lambda:"Hello")
a[1] = 3
a[3] = 2
print(a)
a[2]
print(a)

defaultdict(<function <lambda> at 0x00000207708EEF28>, {1: 3, 3: 2})
defaultdict(<function <lambda> at 0x00000207708EEF28>, {1: 3, 3: 2, 2: 'Hello'})


In [148]:
from collections import deque
a = deque()
a.append(1)
print(a)
a.append(2)
print(a)
a.popleft()
print(a)
a.appendleft(3)
print(a)
a.pop()
print(a)

deque([1])
deque([1, 2])
deque([2])
deque([3, 2])
deque([3])


In [149]:
a = [3, 2, 1, 4, 5, 7]
i = iter(a)
print(next(i))
print(next(i))
print(next(i))

3
2
1


In [150]:
from math import factorial
print(factorial(5))

120


In [151]:
import math
print(math.factorial(5))

120


In [156]:
from itertools import permutations, combinations
a = [1, 2, 3, 4]
print(list(combinations(a, 3)))

[(1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]


In [158]:
from functools import reduce
a = [1, 2, 3, 4]
print(reduce(lambda x, y:x * y, a))

24


In [162]:
from time import time
print(time())

1557836604.0970538


In [2]:
from functools import reduce
a  = [3, 6, 2, 1, 7]
print(reduce(lambda x, y:x*y, a))

252


In [3]:
from math import factorial
print(factorial(5))

120


In [ ]:
1
22
333
4444
55555
666666

In [5]:
[print(((10**i - 1)*i)//9) for i in range(1, 10)]
print()

1
22
333
4444
55555
666666
7777777
88888888
999999999



In [6]:
[print(((10**i - 1)**2)//81) for i in range(1, 10)]

1
121
12321
1234321
123454321
12345654321
1234567654321
123456787654321
12345678987654321


[None, None, None, None, None, None, None, None, None]

In [2]:
def changeValue(a):
    a[2] = 4
a = [1, 2, 3, 4, 5]
changeValue(a)
print(a)

[1, 2, 4, 4, 5]
