In [1]:
a = int(input())
b = int(input())
print(a+b)

5
6
11


In [2]:
a, b = 5, 6
a, b = b, a
print(a, b)

6 5


In [3]:
i = 10
while i > 0:
    print(i)
    i -= 1

10
9
8
7
6
5
4
3
2
1


In [4]:
for i in range(10):
    if i == 4 or i == 8:
        continue
    elif i == 9:
        break
    else:
        print(i)
# or => Python, C++                           || => C, C++, Java
# and => Python, C++                          && => C, C++, Java

0
1
2
3
5
6
7


In [5]:
a = ["Hello", 3, 'c', 4.87]
print(a)

['Hello', 3, 'c', 4.87]


In [6]:
a = ["Hello", 3, 'c', 4.87]
for i in range(len(a)):
    print(a[i])
print()
i = 0
while i < len(a):
    print(a[i])
    i += 1

Hello
3
c
4.87

Hello
3
c
4.87


In [7]:
a = ["Hello", 3, 'c', 4.87]
for i in a:
    print(i)

Hello
3
c
4.87


In [8]:
a = [1, 2, 3, 4, 5]  # [1, 2, 3, 4, 5]
print(a)
print(a[1:])
print(a[:4])
print(a[1:4])
print(a[::2])
print(a[::-1])
print(a[1:4:2])
print(a[3:0:-1])

[1, 2, 3, 4, 5]
[2, 3, 4, 5]
[1, 2, 3, 4]
[2, 3, 4]
[1, 3, 5]
[5, 4, 3, 2, 1]
[2, 4]
[4, 3, 2]


In [9]:
a = [1, 2, 3, 4, 5]
print(a[-4:-1:2])

[2, 4]


In [10]:
a = [1, 2]
b = [3, 4, 5]
print((a+b)*5)
print(a)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2]


In [11]:
a = [1, 2]
b = [3, 4, 5]
a.extend(b)
print(a)

[1, 2, 3, 4, 5]


In [12]:
a = [1, 2]
a.append(3)
print(a)

[1, 2, 3]


In [13]:
a = [1, 2, 3, 4, 5]
print(a)
print(*a)
print(*a, sep="::")
print(1, end=" ")
print(2)

[1, 2, 3, 4, 5]
1 2 3 4 5
1::2::3::4::5
1 2


In [14]:
a = (1, 2, 3, 4, 5)
b = [1, 2, 3, 4, 5]
print(a)
print(b)
a[2] = 2
print(a)
b[2] = 2
print(b)


(1, 2, 3, 4, 5)
[1, 2, 3, 4, 5]


TypeError: 'tuple' object does not support item assignment

In [15]:
a = [3, 1, 5, 2, 4, 7, 6]
print(sum(a))
print(min(a))
print(max(a))

28
1
7


In [16]:
a = input().split()
for i in range(len(a)):
    a[i] = int(a[i])
print(a)

1 2 3 4 5
[1, 2, 3, 4, 5]


In [17]:
a = list(map(int, input().split()))
print(a)

1 2 3 4 5
[1, 2, 3, 4, 5]


In [18]:
a = [1, 2, 3, 4, 5]
a = list(map(lambda x:x+1, a))
print(a)

[2, 3, 4, 5, 6]


In [19]:
a = [3, 1, 5, 2, 4, 7, 6]
a.sort(reverse=True)
print(a)

[7, 6, 5, 4, 3, 2, 1]


In [20]:
a = [3, 1, 5, 2, 4, 7, 6]
print(sorted(a))
print(a)

[1, 2, 3, 4, 5, 6, 7]
[3, 1, 5, 2, 4, 7, 6]


In [21]:
a = 9
b = 4
print(a/b)
print(a//b)

2.25
2


In [22]:
print(2**5)

32


In [23]:
a = [-5, -3, -1, 0, 2, 4, 6]
print(sorted(a, key=lambda x:x**2))

[0, -1, 2, -3, 4, -5, 6]


In [27]:
a = [1, 2, 3, 4, 5]
b = a[:]
b[2] = 2
print(id(a))
print(id(b))
print(a)
print(b)

2325808276552
2325807497736
[1, 2, 3, 4, 5]
[1, 2, 2, 4, 5]


In [26]:
a = 5
b = a
b = 2
print(a, b)
print(id(a), id(b))

5 2
140730934342608 140730934342512


In [29]:
a = [i for i in range(4) if i != 2]
print(a)

[0, 1, 3]


In [32]:
a = [1, 2, 3, 4, 5]
b = "a"
print(eval(b))

[1, 2, 3, 4, 5]


In [37]:
a = set([1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 3, 4, 1, 2, 2])
print(a)

{1, 2, 3, 4}


In [35]:
for i in a:
    print(i, end=" ")

1 2 3 4 

In [38]:
a = {1, 2, 3, 4}
b = {2, 3, 4, 5}
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))

{1, 2, 3, 4, 5}
{2, 3, 4}
{1}


In [39]:
set(map(lambda x:x**2, {-1, 0, 1}))

{0, 1}

In [46]:
a = {"Very Good": 4, "Good":3, "Average":2, "Poor":1}
print(a)
a["Excellent"] = 5
print(a["Brilliant"])

{'Very Good': 4, 'Good': 3, 'Average': 2, 'Poor': 1}


KeyError: 'Brilliant'

In [51]:
from collections import defaultdict
a = defaultdict(lambda:5)
a["Very Good"] = 4
a["Good"] = 3
a["Average"] = 2
a["Poor"] = 1
print(a)
print(a["Excellent"])
print(a)

defaultdict(<function <lambda> at 0x0000021D8505C378>, {'Very Good': 4, 'Good': 3, 'Average': 2, 'Poor': 1})
5
defaultdict(<function <lambda> at 0x0000021D8505C378>, {'Very Good': 4, 'Good': 3, 'Average': 2, 'Poor': 1, 'Excellent': 5})


In [52]:
class Rectangle:
    def __init__(self, l, b):
        self.length = l
        self.breadth = b
    def perimeter(self):
        return (2*(self.length+self.breadth))
    def area(self):
        return (self.length*self.breadth)

In [53]:
myRectangle = Rectangle(5, 4)
print("Length:", myRectangle.length)
print("Breadth:", myRectangle.breadth)
print("Perimeter:", myRectangle.perimeter())
print("Area:", myRectangle.area())

Length: 5
Breadth: 4
Perimeter: 18
Area: 20


In [55]:
class Square(Rectangle):
    def __init__(self, a):
        self.length = self.breadth = a

In [56]:
mySquare = Square(5)
print("Length:", mySquare.length)
print("Breadth:", mySquare.breadth)
print("Perimeter:", mySquare.perimeter())
print("Area:", mySquare.area())

Length: 5
Breadth: 5
Perimeter: 20
Area: 25


In [72]:
class complex_number:
    def __init__(self, a, b):
        self.real = a
        self.imag = b
    def __add__(self, other):
        return complex_number(self.real+other.real, self.imag+other.imag)
    def __sub__(self, other):
        return complex_number(self.real-other.real, self.imag-other.imag)
    def __mul__(self, other):
        return complex_number(self.real*other.real-self.imag*other.imag, self.real*other.imag+other.real*self.imag)
    def __str__(self):
        if self.imag >= 0:
            return str(self.real) + " + " + str(self.imag) + "i"
        else:
            return str(self.real) + " - " + str(-self.imag) + "i"

In [73]:
a = complex_number(1, 2)
b = complex_number(3, -4)
print(a+b)
print(a-b)
print(a*b)

4 - 2i
-2 + 6i
11 + 2i


In [75]:
import math
print(math.pi)
print(math.e)
print(math.exp(2))
print(math.pow(2, 3)) # 2**3
print(math.sqrt(35))

3.141592653589793
2.718281828459045
7.38905609893065
8.0
5.916079783099616


In [79]:
print(math.asin(0))
print(math.sin(math.pi/2))
print(math.acos(0))
print(math.cos(math.pi/2))
print(math.tan(0))

0.0
1.0
1.5707963267948966
6.123233995736766e-17
0.0


In [82]:
from math import ceil, floor
print(ceil(5.5))
print(floor(5.5))
print(round(5.5))

6
5
6


In [87]:
from math import factorial
print(factorial(10))

3628800


In [88]:
a = [1, 2, 3, 4, 5]
i = iter(a)
print(next(i))
print(next(i))
print(next(i))
print(next(i))

1
2
3
4


In [91]:
from collections import Counter
a = [1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2]
a = Counter(a)
print(a)

Counter({1: 7, 2: 5})


In [98]:
from itertools import permutations, combinations
a = [1, 2, 3, 4, 5]
print(list(permutations(a, 2)))
print(list(combinations(a, 2)))

[(1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 3), (2, 4), (2, 5), (3, 1), (3, 2), (3, 4), (3, 5), (4, 1), (4, 2), (4, 3), (4, 5), (5, 1), (5, 2), (5, 3), (5, 4)]
[(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]


In [101]:
from functools import reduce
a = [3, 1, 4, 2, 2]
print(reduce(lambda x,y:x*y, a))

48


In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [4]:
a = np.zeros((4, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
a = np.ones((4, 5))*3
print(a)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [7]:
a = np.random.randn(4, 5)
print(a)

[[-0.40990131 -0.20880639 -0.32139493  0.37865165 -0.11175396]
 [ 0.44311538 -2.42653224 -0.05449939 -0.98951448  0.91812551]
 [-0.45827791 -0.62107737  0.00771901  0.31594978  0.75380827]
 [-0.42966634  0.22690064  1.80856275 -0.08204249  0.03263527]]


In [15]:
a = np.ones((3, 3))
print(a)
a = a / 3
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [17]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.ceil(a))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.round(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.floor(a))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [23]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.square(a))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.power(a, 3))

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [28]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [29]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.log10(a))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


In [30]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [31]:
a = np.random.randn(3, 3)
print(np.arcsin(a))

[[-0.96447421  0.35174902  0.62292341]
 [        nan -0.71607686         nan]
 [-0.72296765         nan -0.78783891]]


C:\Users\Subhadeep\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arcsin
  


In [32]:
a = np.random.randn(3, 3)
print(np.arctan(a))

[[-1.18548878 -0.57519074  0.7697417 ]
 [ 0.30602678 -0.53746493 -0.122673  ]
 [-0.30097552  0.22230972  0.14021736]]


In [33]:
a = np.random.randn(3, 3)
print(np.sqrt(a))

[[       nan        nan 0.34557365]
 [       nan        nan 0.5263893 ]
 [       nan        nan        nan]]


C:\Users\Subhadeep\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [73]:
a = np.random.randn(3, 3)
print(np.abs(a))

[[2.06263495 0.26879782 0.72626674]
 [0.53528678 1.30323832 0.02099557]
 [0.10246049 1.3903318  1.15833202]]


In [82]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1:, 1:])

[[5 6]
 [8 9]]


In [83]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [87]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.linalg.inv(a))
print(np.linalg.det(a))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
-9.51619735392994e-16


In [88]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape)
a = a.reshape(9,)
print(a)

(3, 3)
[1 2 3 4 5 6 7 8 9]


In [90]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 4, 5])
print(np.linalg.norm(a-b))

3.1622776601683795


In [93]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.linalg.norm(a))
print(np.linalg.norm(a, axis = 0))
print(np.linalg.norm(a, axis = 1))

16.881943016134134
[ 8.1240384   9.64365076 11.22497216]
[ 3.74165739  8.77496439 13.92838828]


In [75]:
a = np.random.randn(3, 3)
print(a)
print(np.where(a>0, 1, 0))

[[-0.55410691 -0.97943784  0.99280041]
 [-0.55731338  1.57665767 -0.60551161]
 [-2.16016245 -1.31111548 -0.33879031]]
[[0 0 1]
 [0 1 0]
 [0 0 0]]


In [42]:
a = np.array([[1, 2], [3, 4]])
# 1 2      1 0
# 3 4      1 1
b = np.array([[1, 0], [1, 1]])
print(a)
print(b)
print(np.dot(a, b))
print(a*b)
print(a.shape)

[[1 2]
 [3 4]]
[[1 0]
 [1 1]]
[[3 2]
 [7 4]]
[[1 0]
 [3 4]]
(2, 2)


In [40]:
import time 
a = np.random.randn(100, 100)
b = np.random.randn(100, 100)
start = time.time()
c1 = np.dot(a, b)
end = time.time()
print("Time taken by Numpy multiplication:", end-start)
c2 = np.zeros(a.shape)
start = time.time()
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[1]):
            c2[i][j] += a[i][k]*b[k][j]
end = time.time()
print("Time taken by for loops:", end-start)

Time taken by Numpy multiplication: 0.001994609832763672
Time taken by for loops: 1.4595191478729248


In [43]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.cross(a, b))

[-1  2 -1]


In [48]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.eigvals(a))
print(np.linalg.eig(a))

[-0.37228132  5.37228132]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [67]:
a = np.array([[1, 2, 3], [3, 6, 9], [2, 4, 6]])
c = np.array([1, 2, 3])
print(a.shape)
print(c.shape)
print(a/c)

(3, 3)
(3,)
[[1. 1. 1.]
 [3. 3. 3.]
 [2. 2. 2.]]


In [70]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

45
[12 15 18]
[ 6 15 24]


In [71]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))

1
[1 2 3]
[1 4 7]


In [72]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

9
[7 8 9]
[3 6 9]


In [94]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [95]:
import pandas as pd

In [96]:
pd.read_excel("train1.xlsx")

Class Label  x-box  y-box  width  height  onpix  x-bar  y-bar  x2bar  \
0               9      5     12      3       7      2     10      5      5   
1               4      4     11      6       8      6     10      6      2   
2               7      2      1      3       1      1      8      6      6   
3               2      4      2      5       4      4      8      7      6   
4               1      1      1      3       2      1      8      2      2   
5              10      2      2      4       4      2     10      6      2   
6               7      4      9      6       7      6      7      8      6   
7               6      6      9      5       4      3     10      6      3   
8               3      7     10      5       5      2      6      8      6   
9              10      2      2      3       3      1     10      6      3   
10             10      1      3      2       2      1      8      8      2   
11              8      4      5      5       4      4      7      7      6   
12             10      3      6      4       4      2      6      6      4   
13              3      6     11      7       8      3      7      8      7   
14              8      6      9      8       7      6      8      6      6   
15              7      3      6      4       4      2      6      6      5   
16              2      5      9      7       7     10      9      8      4   
17              7      4      7      6       5      3      6      6      6   
18              7      4      9      5       6      6      8      5      4   
19              5      3      4      3       6      2      3      8      6   
20              5      3      7      4       5      4      7      7      5   
21              7      4      5      5       8      3      7      6      8   
22              7      1      3      2       1      1      7      7      5   
23             10      4      5      6       6      5      8     10      4   
24              4      2      6      3       4      2      6      7     10   
25              3      6     10      4       5      2      6      9      6   
26              3      2      3      3       1      1      5      9      4   
27              5      6      9      4       4      2      7      7      4   
28              8      3      3      4       1      2      8      7      5   
29              8      3      5      5       4      3      7      8      3   
...           ...    ...    ...    ...     ...    ...    ...    ...    ...   
2186            3      7     10      7       7      5      4      8      5   
2187            3      7     10      7       8      4      3      8      6   
2188            1      1      1      2       2      1      7      3      2   
2189            7      3      5      4       7      2      7      6      8   
2190            8      4      7      5       5      4      8      7      6   
2191            6      1      0      1       0      0      4     12      4   
2192            2      4      8      6       6      4      8      8      4   
2193            5      7      9      9       8      9      7      8      5   
2194            8      5      8      7       6      8      7      6      5   
2195            4      3      2      4       3      3      7      7      7   
2196            8      5      9      6       7      6      7      5     13   
2197            7      7     13      6       8      5      7      6      4   
2198            4      5     11      6       8      6      6      7      9   
2199            6      5     11      7       8      4      6     11      2   
2200            9      1      5      2       4      1      7      7      0   
2201            5      2      6      3       4      2      3      6      6   
2202            2      5      7      7       5      5      8      8      4   
2203            2      5      8      7       6      5     10      5      3   
2204            7      6      8      8       7      8      8      6      6   
2205            2     11    

In [100]:
data = pd.read_csv("train.csv")

In [103]:
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [104]:
data.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [108]:
print(data["Age"].mean())
print(data["Age"].var())
print(data["Age"].std())

29.69911764705882
211.0191247463081
14.526497332334044


In [109]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [111]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [115]:
data.drop(columns=["Name", "Ticket", "Cabin"])

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch      Fare  \
0              1         0       3    male  22.0      1      0    7.2500   
1              2         1       1  female  38.0      1      0   71.2833   
2              3         1       3  female  26.0      0      0    7.9250   
3              4         1       1  female  35.0      1      0   53.1000   
4              5         0       3    male  35.0      0      0    8.0500   
5              6         0       3    male   NaN      0      0    8.4583   
6              7         0       1    male  54.0      0      0   51.8625   
7              8         0       3    male   2.0      3      1   21.0750   
8              9         1       3  female  27.0      0      2   11.1333   
9             10         1       2  female  14.0      1      0   30.0708   
10            11         1       3  female   4.0      1      1   16.7000   
11            12         1       1  female  58.0      0      0   26.5500   
12            13         0       3    male  20.0      0      0    8.0500   
13            14         0       3    male  39.0      1      5   31.2750   
14            15         0       3  female  14.0      0      0    7.8542   
15            16         1       2  female  55.0      0      0   16.0000   
16            17         0       3    male   2.0      4      1   29.1250   
17            18         1       2    male   NaN      0      0   13.0000   
18            19         0       3  female  31.0      1      0   18.0000   
19            20         1       3  female   NaN      0      0    7.2250   
20            21         0       2    male  35.0      0      0   26.0000   
21            22         1       2    male  34.0      0      0   13.0000   
22            23         1       3  female  15.0      0      0    8.0292   
23            24         1       1    male  28.0      0      0   35.5000   
24            25         0       3  female   8.0      3      1   21.0750   
25            26         1       3  female  38.0      1      5   31.3875   
26            27         0       3    male   NaN      0      0    7.2250   
27            28         0       1    male  19.0      3      2  263.0000   
28            29         1       3  female   NaN      0      0    7.8792   
29            30         0       3    male   NaN      0      0    7.8958   
..           ...       ...     ...     ...   ...    ...    ...       ...   
861          862         0       2    male  21.0      1      0   11.5000   
862          863         1       1  female  48.0      0      0   25.9292   
863          864         0       3  female   NaN      8      2   69.5500   
864          865         0       2    male  24.0      0      0   13.0000   
865          866         1       2  female  42.0      0      0   13.0000   
866          867         1       2  female  27.0      1      0   13.8583   
867          868         0       1    male  31.0      0      0   50.4958   
868          869         0       3    male   NaN      0      0    9.5000   
869          870         1       3    male   4.0      1      1   11.1333   
870          871         0       3    male  26.0      0      0    7.8958   
871          872         1       1  female  47.0      1      1   52.5542   
872          873         0       1    male  33.0      0      0    5.0000   
873          874         0       3    male  47.0      0      0    9.0000   
874          875         1       2  female  28.0      1      0   24.0000   
875          876         1       3  female  15.0      0      0    7.2250   
876          877         0       3    male  20.0      0      0    9.8458   
877          878         0       3    male  19.0      0      0    7.8958   
878          879         0       3    male   NaN      0      0    7.8958   
879          880         1       1  female  56.0      0      1   83.1583   
880          881         1       2  female  25.0      0      1   26.0000   
881          882         0       3    male  33.0     

In [116]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [122]:
pd.get_dummies(data["Sex"],drop_first=True)

male
0       1
1       0
2       0
3       0
4       1
5       1
6       1
7       1
8       0
9       0
10      0
11      0
12      1
13      1
14      0
15      0
16      1
17      1
18      0
19      0
20      1
21      1
22      0
23      1
24      0
25      0
26      1
27      1
28      0
29      1
..    ...
861     1
862     0
863     0
864     1
865     0
866     0
867     1
868     1
869     1
870     1
871     0
872     1
873     1
874     0
875     0
876     1
877     1
878     1
879     0
880     0
881     1
882     0
883     1
884     1
885     0
886     1
887     0
888     0
889     1
890     1

[891 rows x 1 columns]

In [123]:
pd.get_dummies(data["Embarked"], drop_first=True)

Q  S
0    0  1
1    0  0
2    0  1
3    0  1
4    0  1
5    1  0
6    0  1
7    0  1
8    0  1
9    0  0
10   0  1
11   0  1
12   0  1
13   0  1
14   0  1
15   0  1
16   1  0
17   0  1
18   0  1
19   0  0
20   0  1
21   0  1
22   1  0
23   0  1
24   0  1
25   0  1
26   0  0
27   0  1
28   1  0
29   0  1
..  .. ..
861  0  1
862  0  1
863  0  1
864  0  1
865  0  1
866  0  0
867  0  1
868  0  1
869  0  1
870  0  1
871  0  1
872  0  1
873  0  1
874  0  0
875  0  0
876  0  1
877  0  1
878  0  1
879  0  0
880  0  1
881  0  1
882  0  1
883  0  1
884  0  1
885  1  0
886  0  1
887  0  1
888  0  1
889  0  0
890  1  0

[891 rows x 2 columns]

In [124]:
data["Age"].fillna(data["Age"].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.699118
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.699118
18     31.000000
19     29.699118
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.699118
27     19.000000
28     29.699118
29     29.699118
         ...    
861    21.000000
862    48.000000
863    29.699118
864    24.000000
865    42.000000
866    27.000000
867    31.000000
868    29.699118
869     4.000000
870    26.000000
871    47.000000
872    33.000000
873    47.000000
874    28.000000
875    15.000000
876    20.000000
877    19.000000
878    29.699118
879    56.000000
880    25.000000
881    33.000000
882    22.000000
883    28.000000
884    25.000000
885    39.000000
886    27.000000
887    19.000000
888    29.6991